
#from cmath import pi
#rayon = int(input("saisir un rayon"))
#hauteur = int(input("saisir une hauteur"))
#resultat = 1/3*pi*rayon**2*hauteur
#print(resultat)#


#exercice 2#

#n= int(input("saissir un entier positif"))
#if n%2==0:
        #print("paire")
#else:
    #print("impair")


#exercice 3#
compteur = 0
entier posiif = int(input("saisir un entier")

                    
      

       
       









